In [ ]:
Q1. Ordinal Encoding and Label Encoding both transform categorical variables into numerical values.
The difference is that Ordinal Encoding assigns a numerical value based on the order or rank
of the categories, while Label Encoding assigns a unique numerical value to each category. 
For example, in Ordinal Encoding, the categories "low", "medium", and "high" might be
assigned values of 1, 2, and 3 based on their order, while in Label Encoding, 
they would be assigned values of 1, 2, and 3 without any inherent order. 
One might choose Ordinal Encoding when there is a natural order or hierarchy among the 
categories, such as in a rating system, while Label Encoding might be chosen when there
is no natural order, such as in a set of color categories.

Q2. Target Guided Ordinal Encoding is a method of encoding categorical variables that 
takes into account the relationship between the categorical variable and the target variable 
in a machine learning problem. The encoding assigns a numerical value to each category based 
on its mean target value. For example, in a binary classification problem where the target
variable is "Survived" and the categorical variable is "Gender", the encoding might assign
a value of 1 to the category "Female" if the mean survival rate for females is higher than 
the mean survival rate for males. Target Guided Ordinal Encoding can be useful in cases where 
the relationship between the categorical variable and the target variable is important for 
predicting the target variable.

Q3. Covariance is a measure of the joint variability of two random variables. 
It measures how much two variables vary together, or in other words, how much they
co-vary. Covariance is important in statistical analysis because it helps to determine
the strength and direction of the relationship between two variables. 
A positive covariance indicates that the variables tend to increase or decrease together,
while a negative covariance indicates that they tend to move in opposite directions. 
Covariance is calculated by taking the product of the deviations of each variable from 
its mean and summing those products over all observations


In [18]:
#Q4.
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
import pandas as pd

# create an example dataframe with three categorical columns
df = pd.DataFrame({
    'Color': ['red', 'green', 'blue', 'red', 'green'],
    'Size': ['small', 'large', 'medium', 'small', 'medium'],
    'Material': ['wood', 'plastic', 'metal', 'wood', 'plastic']
})

# create a LabelEncoder object and fit_transform the 'Color' column
le = LabelEncoder()
df['Color'] = le.fit_transform(df['Color'])

# create an OrdinalEncoder object and fit_transform the 'Size' and 'Material' columns
oe = OrdinalEncoder(categories=[['small', 'medium', 'large'], ['wood', 'metal', 'plastic']])
df[['Size', 'Material']] = oe.fit_transform(df[['Size', 'Material']])

print(df)


   Color  Size  Material
0      2   0.0       0.0
1      1   2.0       2.0
2      0   1.0       1.0
3      2   0.0       0.0
4      1   1.0       2.0


In [4]:
#Q5. 
data = {'Age': [25, 30, 35, 40, 45],
        'Income': [50000, 60000, 75000, 90000, 100000],
        'Education Level': [1, 2, 3, 3, 4]}

df = pd.DataFrame(data)

covariance_matrix = df.cov()

print(covariance_matrix)


                       Age       Income  Education Level
Age                  62.50     162500.0             8.75
Income           162500.00  425000000.0         22500.00
Education Level       8.75      22500.0             1.30


In [ ]:
Q6. For "Gender", since there are only two categories, we can use binary encoding or label encoding. 
For "Education Level", we can use ordinal encoding since there is a clear order between the categories
(i.e., High School < Bachelor's < Master's < PhD). For "Employment Status", 
we can use one-hot encoding since there is no inherent order between the categories and we want 
to avoid imposing any ordinal relationship between them.

In [23]:
#Q7.
import numpy as np

# Example data with two continuous variables and two categorical variables
temperature = np.array([25, 27, 22, 20, 24])
humidity = np.array([60, 65, 55, 50, 58])
weather_condition = np.array(['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Cloudy'])
wind_direction = np.array(['North', 'South', 'East', 'West', 'North'])

# Encode the categorical variables using one-hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
weather_condition_encoded = encoder.fit_transform(weather_condition.reshape(-1, 1)).toarray()
wind_direction_encoded = encoder.fit_transform(wind_direction.reshape(-1, 1)).toarray()

# Concatenate the encoded variables with the continuous variables
X = np.concatenate((temperature.reshape(-1, 1), humidity.reshape(-1, 1), 
                    weather_condition_encoded, wind_direction_encoded), axis=1)

# Calculate the covariance matrix
covariance_matrix = np.cov(X, rowvar=False)

print(covariance_matrix)



[[ 7.3  15.05  0.95 -0.4  -0.55 -0.4   0.45  0.85 -0.9 ]
 [15.05 31.3   1.95 -0.65 -1.3  -0.65  0.7   1.85 -1.9 ]
 [ 0.95  1.95  0.3  -0.1  -0.2  -0.1   0.05  0.15 -0.1 ]
 [-0.4  -0.65 -0.1   0.2  -0.1   0.2  -0.1  -0.05 -0.05]
 [-0.55 -1.3  -0.2  -0.1   0.3  -0.1   0.05 -0.1   0.15]
 [-0.4  -0.65 -0.1   0.2  -0.1   0.2  -0.1  -0.05 -0.05]
 [ 0.45  0.7   0.05 -0.1   0.05 -0.1   0.3  -0.1  -0.1 ]
 [ 0.85  1.85  0.15 -0.05 -0.1  -0.05 -0.1   0.2  -0.05]
 [-0.9  -1.9  -0.1  -0.05  0.15 -0.05 -0.1  -0.05  0.2 ]]
